In [5]:
import pandas as pd
import sqlite3

In [6]:
conn = sqlite3.connect('data/bible.eng.db')

In [3]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, conn)
tables

                      name
0       _prisma_migrations
1              Translation
2                     Book
3                  Chapter
4             ChapterVerse
5          ChapterFootnote
6          ChapterAudioUrl
7               Commentary
8           CommentaryBook
9        CommentaryChapter
10  CommentaryChapterVerse
11                 Dataset
12             DatasetBook
13          DatasetChapter
14     DatasetChapterVerse
15        DatasetReference

In [ ]:
query = """
SELECT 
    t.shortName AS translation,
    t.englishName AS translation_name,
    cv.text
FROM ChapterVerse cv
JOIN Book b ON cv.bookId = b.id AND cv.translationId = b.translationId
JOIN Translation t ON cv.translationId = t.id
WHERE b.commonName = 'Romans'
  AND cv.chapterNumber = 1
  AND cv.number = 17
ORDER BY t.shortName;
"""
romans_1_17 = pd.read_sql_query(query, conn)
pd.set_option('display.max_colwidth', None)
romans_1_17

,translation,translation_name,text
0,ASV,American Standard Version (1901),For therein is revealed a righteousness of God...
1,ASVBT,ASV Byzantine Text,For therein is revealed a righteousness of God...
2,BBE,Bible in Basic English,For in it there is the revelation of the right...
3,BSB,Berean Standard Bible,For the gospel reveals the righteousness of Go...
4,DBY,Darby Translation,"for righteousness of God is revealed therein, ..."
5,DRA,Douay-Rheims 1899,"For the justice of God is revealed therein, fr..."
6,EMTV,English Majority Text Version,For in it the righteousness of God is revealed...
7,FBV,Free Bible Version,For in the good news God is revealed as good a...
8,GNB,Noyes Bible,For therein is revealed the righteousness whic...
9,GNV,Geneva Bible 1599,For by it the righteousnesse of God is reueile...
10,KJAV,King James Version,For therein is the righteousness of God reveal...
11,KJVA,King James Version + Apocrypha,For therein is the righteousness of God reveal...
12,KJVCP,KJV Cambridge Paragraph,For therein is the righteousness of God reveal...
13,LSV,English LSV,For the righteousness of God in it is revealed...
14,MSB,Majority Standard BIble,For the gospel reveals the righteousness of Go...
15,NETB,NET Bible,For the righteousness of God is revealed in th...
16,NWB,Webster Bible,For in this is the righteousness of God reveal...
17,PEV,Plain English Version,God’s good news is this. God saves people that...
18,RVA,Revised Version,For therein is revealed a righteousness of God...
19,T4T,Translation for Translators,By means of this good message God reveals how ...
20,TCENT,Text-Critical English NT,For in it the righteousness of God is revealed...
21,TNT,Tyndale NT,For by it the rightewesnes which cometh of god...
22,TNTC,Family 35 NT,"because in it God's righteousness is revealed,..."
23,TOJB,The Orthodox Jewish Bible - Tanakh and Orthod...,"For the Tzidkat Hashem, (the righteousness of ..."
24,ULB,Unlocked Literal Bible,For in it God's righteousness is revealed from...
25,WBMS,English: Wycliffe's Bible Modern Spelling (wit...,"For the rightwiseness of God is showed in it, ..."
26,WBMSE,English: Wycliffe's Bible Modern Spelling (Enh...,"For the rightwiseness of God is showed in it, ..."
27,WEB,World English Bible,For in it is revealed God’s righteousness from...
28,WEBBE,World English Bible British Edition,For in it is revealed God’s righteousness from...
29,WEBBE,World English Bible British Edition with Deute...,For in it is revealed God’s righteousness from...
30,WEBC,World English Bible Classic,For in it is revealed God’s righteousness from...
31,WEBC,World English Bible (Catholic),For in it is revealed God’s righteousness from...
32,WEBU,World English Bible Updated,For in it is revealed God’s righteousness from...
33,WMB,World Messianic Bible,For in it is revealed God’s righteousness from...
34,WMBBE,World Messianic Bible British Edition,For in it is revealed God’s righteousness from...
35,YLT,Young's Literal Translation,For the righteousness of God in it is revealed...